version: '3.3'

services:
  docker-hub-exporter:
    container_name: docker-hub-exporter
    image: infinityworks/docker-hub-exporter:latest
    command:
      - -organisations=fluent
    networks:
      - nginx-log-exporter
    ports:
      - 9170:9170

  nginx-log-exporter:
    container_name: nginx-log-exporter
    image: quay.io/nginx-log-exporter/nginx-log-exporter-linux-amd64:main
    volumes:
      - ./example-access.log:/access.log
    command: /nginx-log-exporter -export_address 0.0.0.0:9180 -access_log_path /access.log -access_log_format CLF -log_polling_period 10s  -monitored_paths '.*.deb','*.rpm' -custom_labels releases=fluent-bit
    networks:
      - nginx-log-exporter
    ports:
      - 9180:9180
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    user: root
    volumes:
      - prometheus-data:/data
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/data
    networks:
      - nginx-log-exporter
    ports:
      - 9090:9090
volumes:
  prometheus-data:
  grafana-data:
   # driver: local

networks:
  nginx-log-exporter:
    driver: bridge