{
 "title": "Crypto-Exporter Ethereum",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "comision_banco_local", "label": "Comision de banco CL (%)", "query": "1.13" },
   { "name": "comision_bitstamp_deposito", "label": "Comision Bitstamp Deposito (%)", "query": "0.005" },
   { "name": "comision_bitstamp_retiro_eth", "label": "Comision Bitstamp Retiro (ETH)", "query": "0.07" },
   { "name": "comision_buda_venta", "label": "Comision Buda Venta (%)", "query": "0.7" },
   { "name": "cantidad_compra_eth", "label": "Cantidad Compra (ETH)", "query": "1,2.5,5,10" }
  ]
 },
 "panels": [
  { "title": "Margenes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Margen de ganancia (Con comisiones)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 + on() (buda_quote{currency=\"eth_clp\", type=\"ask_given_size\"} * $cantidad_compra_eth - on() ((bitstamp_bid_price{currency=\"eth_usd\"} * $cantidad_compra_eth * on(instance) dollar_current_price )) * 100) / on() (buda_quote{currency=\"eth_clp\", type=\"ask_given_size\"} * $cantidad_compra_eth - on()  (ethereum_average_contract_transfer_fee * on()  dollar_current_price))) - on () ($comision_bitstamp_retiro_eth+$comision_buda_venta+$comision_bitstamp_deposito+$comision_bitstamp_retiro_eth) \n "
    }
   ]
  },
  {
   "title": "Precios ETH (CLP)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CLP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "buda_last_trade{currency=\"eth_clp\"} * on() $cantidad_compra_eth",
     "legendFormat": "Buda (CLP)"
    },
    {
     "expr": "(bitstamp_last_trade{currency=\"eth_usd\"} * on() dollar_current_price) * on() $cantidad_compra_eth",
     "legendFormat": "Bitstamp (CLP)"
    },
    {
     "expr": "(buda_last_trade{currency=\"eth_clp\"} - on() (bitstamp_last_trade{currency=\"eth_usd\"} * on() dollar_current_price)) * on() $cantidad_compra_eth",
     "legendFormat": "Margen (CLP)"
    }
   ]
  },
  {
   "title": "Costo Transferencia ETH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "clp" } },
   "yaxes": [
    { "format": "clp" }
   ],
   "targets": [
    {
     "expr": "ethereum_average_contract_transfer_fee * on() dollar_current_price"
    }
   ]
  },
  {
   "title": "Margen (Sin comisiones) ETH (Bitstamp -> Buda)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 + on() (buda_quote{currency=\"eth_clp\", type=\"ask_given_size\"} * $cantidad_compra_eth - on() ((bitstamp_bid_price{currency=\"eth_usd\"} * $cantidad_compra_eth * on(instance) dollar_current_price )) * 100) / on() (buda_quote{currency=\"eth_clp\", type=\"ask_given_size\"} * $cantidad_compra_eth))"
    }
   ]
  },
  {
   "title": "CLP por Cantidad de compra (ETH)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "CLP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(bitstamp_bid_price{currency=\"eth_usd\"} * on(instance) dollar_current_price) * on() $cantidad_compra_eth"
    }
   ]
  }
 ]
}