# prometheus global config
global:
  scrape_interval:     10s
  evaluation_interval: 30s

scrape_configs:

  - job_name: nginx-log-exporter
    scrape_interval: 10s
    scrape_timeout: 9s
    static_configs:
      - targets: ["nginx-log-exporter:9180"]